#!/bin/bash

if [ "" == "$ROOT_DIR" ]; then

  set -o pipefail

  ROOT_DIR="$(dirname "$SCRIPT_DIR")"
  
  if [ "`uname`" = "Darwin" ]; then
  	MAC_NATIVE=1
  else
  	MAC_NATIVE=0
  fi
  if [ "`uname -o 2> /dev/null`" = "Cygwin" ]; then
  	WIN_NATIVE=1
  else
  	WIN_NATIVE=0
  fi
  
  FAIL_CMD='echo -e \033[31;1mFAIL\033[0m'
  FAILED=0
  
  . "$ROOT_DIR/config.sh"
fi
