#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $SCRIPT_DIR/check_requirements_common
. $SCRIPT_DIR/check_requirements_build continue

echo
echo "Checking packaging requirements:"
echo

if [ $WIN_NATIVE == 1 ]; then
	echo -n "Checking for upx: "
	which upx || { $FAIL_CMD; FAILED=1; }

	echo -n "Checking for uuidgen: "
	which uuidgen || { $FAIL_CMD; FAILED=1; }
	
	echo -n "Checking for signtool: "
	if [ -x "`cygpath -u \"$SIGNTOOL\"`" ]; then
		echo "`cygpath -u \"$SIGNTOOL\"`"
	else
		$FAIL_CMD
		FAILED=1
	fi
	
	echo -n "Checking for Unicode NSIS: "
	if [ -x "`cygpath -u \"${NSIS_DIR}makensis.exe\"`" ]; then
		echo "`cygpath -u \"${NSIS_DIR}makensis.exe\"`"
	else
		$FAIL_CMD
		FAILED=1
	fi
	
	plugin_path=$(cd "$NSIS_DIR\\Plugins" && pwd)
	plugins="AppAssocReg ApplicationID InvokeShellVerb ShellLink UAC"
	echo "Checking for NSIS plugins in $plugin_path"
	for i in $plugins; do
		echo -n "  $i.dll: "
		if [ -f "$plugin_path/$i.dll" ]; then
			echo OK
		else
			$FAIL_CMD
			FAILED=1
		fi
	done
fi

if [ $MAC_NATIVE == 1 ]; then
	echo -n "Checking for codesign: "
	which /usr/bin/codesign || { $FAIL_CMD; FAILED=1; }
fi



if [ "$1" != "continue" ]; then
  exit $FAILED
fi
